---
title: "Executive Summary"
subtitle: "Armed Conflicts in Nigeria - Grundlegendes Praxisprojekt [w24/25]"
author: "Group 8: Danh Chau Ngo, Paul Seitz, Marc Landes, Yuxin Qiu, Shuangying Xu"
date: "2025-04-02"
format: pdf
editor: 
  markdown: 
    wrap: sentence
---

## Introduction

The goal of this course was for the students to descriptively analyse a data set.
This group in particular received a data set about armed conflicts in Nigeria.
Two main questions were given.

-   

    1)  Is there an association between type of conflict and conflict groups?

-   

    2)  Is there a change in the type of conflict observable over time?


## Data Structure

The Data is sourced from the Armed Conflict Location and Event Data Project.
(see https://acleddata.com/)
It consists of 70897 observations with 39813 unique IDs.
There are 19 variables in the raw data.
Each observation is an event in Nigeria, for example a battle, a protest, a strategic development, etc..
There is a "notes" variable, which gives detailed information about each event.
Dates range from 1997 to 2025.
Most of the observations include geographical coordinates and time stamps.
Some variables like "actor" or "sub_event_type" vary vastly,
for example the "actor" column counts 1439 unique strings.
The Data is structured in a way which enables network analysis.
There are up to 2 actors for an event, which represent involved parties in a conflict.
Interestingly, not every ID has two actors.
For Example protests, riots or strategic developments can have only one actor.
So the data includes network data, but is not purely network data.
Also, in cases where there are 2 actors, edges are not directed.
There is a boolean variable "civilian_targeting" and a value "Violence against
Civilians" of a variable "event_type". These enable a more efficient analysis of
the civilian role in the events and counteract the undirectedness of the data.
The largest challenges which arise from the data structure are the following:

-   

    1)  Simplification: Variables had to be categorized to make visualisation meaningful, guidelines were taken from ACLED's guide, except when single values outnumbered categories (see Boko/Haram and ISWAP)

-   

    2)  Dealing with the undirected Network: Sadly, questions like "How often did Boko Haram use IEDs?" cannot be answered in this setting, but one can answer questions like "How often was there an IED event which was done by or was directed at Boko Haram". So, questions of directedness cannot be answered easily.

These may also be seen as the limitations as 1) implies that detail has to be sacrificed in some situations
to enable any analysis at all. And also 2) shows that some questions which may be of great interest simply 
cannot be answered.

## Results

The types of conflicts vary, and include violent action like attacks, but also peaceful action like protests.
Event intensity seems to have increased since 2010, but one must consider that this may also be an artifact
due to there being a higher willingness to report events. Under the same limitations, there seems also
to be an increase in the rate of battles in both 2010 and 2020. The 3 actor categories which are associated
with the most fatalities in events are identity militias, the state forces and ISWAP/Boko Haram, with
each being involved in conflicts which had fatality counts of approximately 50000.
Out of the three, the state forces are responsible for the smallest amount of civilian fatalities.
The actor categories differ in their means of violence, for example ISWAP/Boko Haram is associated with 
a high number of suicide attacks, when compared to the other groups with high total fatality counts.
There is a geographical pattern. Out of the three aforementioned groups, ISWAP/Boko Haram is active 
almost exclusively in the Northeast, whilst identity militias are active in the West and South.
State forces seem to be active in all of Nigeria. Protest and Riots seem to be happening more often in the 
South, but this may also be due to a higher population per area.
The group pairs which had the highest amount of fatalities in shared events were (state forces - ISWAP/Boko Haram), (ISWAP/Boko Haram - civilians), (civilians - identity militias), (identity militias - state forces).
